(package "lsp-treemacs"
         "0.4"
         "LSP treemacs")

(package-file "lsp-treemacs.el")

(files "*.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "dash")
(depends-on "f")
(depends-on "ht")
(depends-on "treemacs")
(depends-on "lsp-mode")

(development
 (depends-on "spinner"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
